name = "Pixell"
uuid = "d4cbf8b2-a14f-4080-9f5e-d5a64ada768e"
authors = ["Zack Li", "Yilun Guan"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
Libsharp = "ac8d63fe-4615-43ae-9860-9cd4a3820532"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"
WCS = "15f3aee2-9e10-537f-b834-a6fb8bdb944d"

[compat]
ColorSchemes = "3"
Colors = "0.11, 0.12"
DSP = "0.7"
FFTW = "1"
FITSIO = "0.16"
FastTransforms = "0.13"
Healpix = "3"
Libsharp = "0.2"
RecipesBase = "1"
StaticArrays = "1"
Unitful = "1"
UnitfulAngles = "0.5, 0.6"
WCS = "0.6.1"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "Plots"]
